#!/bin/bash

webhook="$1"
debug="FALSE"
feeds="./feeds.txt"
logs="./logs"
libs="./libs"
db_file="./urls.db"
db="urls"
schema="./conf/db.schema"
rightnow=`date -d "today" +"%Y%m%d%H%M"`
log_filename="$rightnow.new"

# Helper functions

debug() {
  if [ "$debug" == "TRUE" ]; then
    echo $1
  fi
}
