#!/bin/bash

debug="$1"
webhook="$2"
feeds="./feeds.txt"
logs="./logs"
libs="./libs"
db_file="./urls.db"
db="urls"
schema="./conf/db.schema"
rightnow=`date -d "today" +"%Y%m%d%H%M"`
log_filename="$rightnow.new"

# Helper functions

debug() {
  if [ "$debug" == "TRUE" ]; then
    echo "$1"
  fi
}

log() {
  echo "$1" >> $logs/run.log
}
